### ISSUE TITLE
Are you planning to launch Reactor with Foundation 5

### ISSUE THREAD

**Issue by ekalavya2014** [awtheme/reactor#79]
Hi Anthony,

Thanks for such an awesome theme, i personally liked the theme very much. 

I hope you are planning to launch Reactor with Foundation 5. Because there are many things which is updated on Foundation 5. If you are planning to do so, should we wait for the launch or use this theme.

Hey sorry it is now an issue but did not got anything from which i could contact you.

Thanks

**Comment by isarmstrong** [comment]
Anthony hasn’t updated Reactor in over two years, I don’t expect he’ll do so any time soon. Most WordPress/Foundation development has moved here: 

https://foundationpress.olefredrik.com/ <https://foundationpress.olefredrik.com/>
https://github.com/olefredrik/FoundationPress <https://github.com/olefredrik/FoundationPress>

As it’s 2015, however, I’d give the UIKit starter themes for WordPress a good hard look. If I were still doing custom theme work, I’d be basing them on UIKit instead of Foundation. It’s lighter and far more modular.

**Comment by JKdreaming** [comment]
Or you could just build your own thing from scratch using whatever framework that you want to. I know this sounds tough but it's really not. You may also say well what about all these layouts? I say don't worry about them, just use the divi plugin. With the Divi plug-in all you need to do is actually create the shell of your website. This gives you the ability to treat super clean code for word press themes from scratch without having to worry about custom fields ever. The divi builder is a plug-in available with your elegant themes subscription. It may sound crazy, but really check it out.

**Comment by ekalavya2014** [comment]
Thanks @isarmstrong and @JKdreaming  for suggestions. I am doing the same, implementing foundation on a theme which is not resposive.
